# Generated by Django 4.0 on 2022-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position1', models.CharField(max_length=20)),
                ('Apps', models.CharField(max_length=20)),
                ('Mins', models.FloatField()),
                ('Goals', models.FloatField()),
                ('Assists', models.FloatField()),
                ('SpG', models.FloatField()),
                ('KeyP', models.FloatField()),
                ('Drb', models.FloatField()),
                ('Fouled', models.FloatField()),
                ('Off', models.FloatField()),
                ('Disp', models.FloatField()),
                ('UnsTch', models.FloatField()),
            ],
        ),
    ]
