# Generated by Django 4.0 on 2022-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='defensive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position1', models.CharField(max_length=20)),
                ('position2', models.CharField(max_length=20)),
                ('Apps', models.CharField(max_length=20)),
                ('Mins', models.FloatField()),
                ('Tackles', models.FloatField()),
                ('Inter', models.FloatField()),
                ('Fouls', models.FloatField()),
                ('Offsides', models.FloatField()),
                ('Clear', models.FloatField()),
                ('Drb', models.FloatField()),
                ('Blocks', models.FloatField()),
                ('OwnG', models.FloatField()),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
