# Generated by Django 4.2.5 on 2023-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_foot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
