# Generated by Django 4.2.5 on 2023-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('acceleration', models.FloatField()),
                ('sprint_speed', models.FloatField()),
                ('agility', models.FloatField()),
                ('stamina', models.FloatField()),
                ('aggression', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
